feat: initial zero deployment (#233)
* Setup Zero package

* Checkpoint

* Fixes

* Fixes

* Progress!

* More changes

* Squash merge main into zero-experimentation

* More progress

* Bump schema version

* Progress

* Fixes

* GH actions tasks for migrations are done

* Cleanup

* Cleanup

* Done

* Fix broken import - use await import

* Add back pre-push hook

* Updates

---------

Co-authored-by: Kian Bazza <kianbazza@Kians-MacBook-Pro.local>

Use updated json import syntax

Fixes

Fix

fix(ci): missing client-side Zero server URL in Dockerfile

Fix

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -16,6 +16,7 @@ jobs:
     runs-on: ubuntu-24.04
     outputs:
       new_version: ${{ steps.determine_version.outputs.new_version }}
+      zero_version: ${{ steps.determine_zero_version.outputs.zero_version }}
     permissions:
       contents: write
       packages: write
@@ -54,6 +55,13 @@ jobs:
           NEW_VERSION=$(pnpm release --ci --release-version | tail -n1)
           echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
 
+      - name: Determine Zero server version
+        id: determine_zero_version
+        run: |
+          ZERO_VERSION=$(yq e '.packages | keys | .[] | select(test("@rocicorp/zero@"))' pnpm-lock.yaml | grep @rocicorp/zero | cut -f 3 -d @)
+          echo "Zero version: $ZERO_VERSION"
+          echo "zero_version=$ZERO_VERSION" >> $GITHUB_OUTPUT
+
   build-push-amd64:
     name: Build & push ${{ matrix.app }} - x64 (AMD64)
     runs-on: ubuntu-24.04
@@ -67,12 +75,10 @@ jobs:
         include:
           - app: web
             dockerfile: ./apps/web/Dockerfile
-          - app: api
-            dockerfile: ./apps/api/Dockerfile
-          - app: sync
-            dockerfile: ./apps/sync/Dockerfile
-          # - app: migrate
-          #   dockerfile: ./packages/database/Dockerfile
+          # - app: api
+          #   dockerfile: ./apps/api/Dockerfile
+          # - app: sync
+          #   dockerfile: ./apps/sync/Dockerfile
 
     steps:
       - name: Checkout monorepo
@@ -131,12 +137,10 @@ jobs:
         include:
           - app: web
             dockerfile: ./apps/web/Dockerfile
-          - app: api
-            dockerfile: ./apps/api/Dockerfile
-          - app: sync
-            dockerfile: ./apps/sync/Dockerfile
-          # - app: migrate
-          #   dockerfile: ./packages/database/Dockerfile
+          # - app: api
+          #   dockerfile: ./apps/api/Dockerfile
+          # - app: sync
+          #   dockerfile: ./apps/sync/Dockerfile
 
     steps:
       - name: Checkout monorepo
@@ -201,7 +205,8 @@ jobs:
         run: |
           VERSION=${{ needs.prepare.outputs.new_version }}
 
-          APPS=("web" "api" "sync")
+          # APPS=("web" "api" "sync")
+          APPS=("web")
 
           for app in "${APPS[@]}"; do
             DIGEST_AMD64=$(docker manifest inspect ghcr.io/avelinapp/$app:${{ github.sha }}-amd64 | jq -r '.manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest')
@@ -229,176 +234,150 @@ jobs:
             docker manifest push ghcr.io/avelinapp/$app:v$VERSION
           done
 
-  update-manifests-bazzalabs-orion:
-    name: Update manifests in bazzalabs/orion
-    runs-on: ubuntu-24.04
-    needs: [prepare, create-manifests]
-    permissions:
-      contents: write
-
-    steps:
-      - name: Checkout IaC repo
-        uses: actions/checkout@v4
-        with:
-          repository: bazzalabs/orion
-          token: ${{ secrets.GH_BAZZALABS_ORION_SECRET }}
-          fetch-depth: 0
-          path: bazzalabs-orion
-
-      - name: Update K8s manifests
-        working-directory: bazzalabs-orion
-        run: |
-          VERSION=v${{ needs.prepare.outputs.new_version }}
-          apps=("web" "api" "sync")
-          manifests_dir="gitops/cluster-apps/avelin"
-          for app in "${apps[@]}"; do
-            manifest="$manifests_dir/$app/${app}-deploy.yaml"
-            if [ -f "$manifest" ]; then
-              echo "Updating image tag in $manifest to $VERSION"
-              yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/$app:$VERSION\"" "$manifest"
-            else
-              echo "Manifest file $manifest not found!"
-              exit 1
-            fi
-          done
-
-          # manifest="$manifests_dir/shared/db-migration-job.yaml"
-          # if [ -f "$manifest" ]; then
-          #   echo "Updating image tag in $manifest to $VERSION"
-          #   yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/migrate:$VERSION\"" "$manifest"
-          # else
-          #   echo "Manifest file $manifest not found!"
-          #   exit 1
-          # fi
-
-      - name: Commit and Push IaC changes
-        working-directory: bazzalabs-orion
-        run: |
-          git config user.name "${{ github.actor }}"
-          git config user.email "${{ github.actor }}@users.noreply.github.com"
-          git add .
-          git commit -m "chore: update manifests to v${{ needs.prepare.outputs.new_version }}"
-          git push
-
-  update-manifests-avelinapp-iac:
-    name: Update manifests in avelinapp/iac
-    runs-on: ubuntu-24.04
-    needs: [prepare, create-manifests]
-    permissions:
-      contents: write
-
-    steps:
-      - name: Checkout IaC repo
-        uses: actions/checkout@v4
-        with:
-          repository: avelinapp/iac
-          token: ${{ secrets.GH_IAC_SECRET }}
-          fetch-depth: 0
-          path: avelinapp-iac
-
-      - name: Update K8s manifests
-        working-directory: avelinapp-iac
-        run: |
-          VERSION=v${{ needs.prepare.outputs.new_version }}
-          apps=("web" "api" "sync")
-          manifests_dir="gitops/cluster-apps/avelin"
-          for app in "${apps[@]}"; do
-            manifest="$manifests_dir/$app/${app}-deploy.yaml"
-            if [ -f "$manifest" ]; then
-              echo "Updating image tag in $manifest to $VERSION"
-              yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/$app:$VERSION\"" "$manifest"
-            else
-              echo "Manifest file $manifest not found!"
-              exit 1
-            fi
-          done
-
-          # manifest="$manifests_dir/shared/db-migration-job.yaml"
-          # if [ -f "$manifest" ]; then
-          #   echo "Updating image tag in $manifest to $VERSION"
-          #   yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/migrate:$VERSION\"" "$manifest"
-          # else
-          #   echo "Manifest file $manifest not found!"
-          #   exit 1
-          # fi
-
-      - name: Commit and Push IaC changes
-        working-directory: avelinapp-iac
-        run: |
-          git config user.name "${{ github.actor }}"
-          git config user.email "${{ github.actor }}@users.noreply.github.com"
-          git add .
-          git commit -m "chore: update manifests to v${{ needs.prepare.outputs.new_version }}"
-          git push
-
-  create-release:
-    name: Create GitHub Release
-    runs-on: ubuntu-latest
-    needs: [update-manifests-bazzalabs-orion, update-manifests-avelinapp-iac]
-    permissions:
-      contents: write
-
-    steps:
-      - name: Checkout monorepo
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Configure Git
-        run: |
-          git config user.name "${{ github.actor }}"
-          git config user.email "${{ github.actor }}@users.noreply.github.com"
-
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          run_install: false
-
-      - name: Install Node.js 20
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: "package.json"
-          architecture: "x64"
-          cache: "pnpm"
-
-      - name: Install dependencies
-        run: pnpm install
-
-      - name: Create GitHub release
-        run: pnpm release --ci
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-  run-migrations:
-    name: Run migrations
-    runs-on: ubuntu-24.04
-    steps:
-      - name: Checkout monorepo
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: Install pnpm
-        uses: pnpm/action-setup@v4
-        with:
-          run_install: false
-
-      - name: Install Node.js 20
-        uses: actions/setup-node@v4
-        with:
-          node-version-file: "package.json"
-          architecture: "x64"
-          cache: "pnpm"
-
-      - name: Install dependencies
-        run: pnpm install
-
-      - name: Migrate database
-        env:
-          DATABASE_URL: ${{ secrets.DATABASE_URL }}
-          CI: true
-        run: |
-          echo "DATABASE_URL=$DATABASE_URL" >> packages/database/.env
-          echo "CI=$CI" >> packages/database/.env
-          pnpm run db:migrate
-          rm packages/database/.env
+  # update-manifests:
+  #   name: Update manifests in avelinapp/iac
+  #   runs-on: ubuntu-24.04
+  #   needs: [prepare, create-manifests]
+  #   permissions:
+  #     contents: write
+  #
+  #   steps:
+  #     - name: Checkout IaC repo
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: avelinapp/iac
+  #         token: ${{ secrets.GH_IAC_SECRET }}
+  #         fetch-depth: 0
+  #         path: avelinapp-iac
+  #
+  #     - name: Update K8s manifests
+  #       working-directory: avelinapp-iac
+  #       run: |
+  #         VERSION=v${{ needs.prepare.outputs.new_version }}
+  #         apps=("web" "api" "sync")
+  #         manifests_dir="gitops/cluster-apps/avelin"
+  #         for app in "${apps[@]}"; do
+  #           manifest="$manifests_dir/$app/${app}-deploy.yaml"
+  #           if [ -f "$manifest" ]; then
+  #             echo "Updating image tag in $manifest to $VERSION"
+  #             yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/$app:$VERSION\"" "$manifest"
+  #           else
+  #             echo "Manifest file $manifest not found!"
+  #             exit 1
+  #           fi
+  #         done
+  #
+  #     - name: Update Zero server manifest
+  #       working-directory: avelinapp-iac
+  #       run: |
+  #         ZERO_VERSION=${{ needs.prepare.outputs.zero_version }}
+  #         manifests_dir="gitops/cluster-apps/avelin"
+  #         manifest="$manifests_dir/zero/zero-deploy.yaml"
+  #         if [ -f "$manifest" ]; then
+  #           echo "Updating Zero server container image tag in $manifest to $ZERO_VERSION"
+  #           yq e -i ".spec.template.spec.containers[].image = \"rocicorp/zero:$ZERO_VERSION\"" "$manifest"
+  #         else
+  #           echo "Manifest file $manifest not found!"
+  #           exit 1
+  #         fi
+  #
+  #     - name: Commit and Push IaC changes
+  #       working-directory: avelinapp-iac
+  #       run: |
+  #         git config user.name "${{ github.actor }}"
+  #         git config user.email "${{ github.actor }}@users.noreply.github.com"
+  #         git add .
+  #         git commit -m "chore: update manifests to v${{ needs.prepare.outputs.new_version }}"
+  #         git push
+  #
+  # create-release:
+  #   name: Create GitHub Release
+  #   runs-on: ubuntu-latest
+  #   needs: [update-manifests]
+  #   permissions:
+  #     contents: write
+  #
+  #   steps:
+  #     - name: Checkout monorepo
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #
+  #     - name: Configure Git
+  #       run: |
+  #         git config user.name "${{ github.actor }}"
+  #         git config user.email "${{ github.actor }}@users.noreply.github.com"
+  #
+  #     - name: Install pnpm
+  #       uses: pnpm/action-setup@v4
+  #       with:
+  #         run_install: false
+  #
+  #     - name: Install Node.js 20
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: "package.json"
+  #         architecture: "x64"
+  #         cache: "pnpm"
+  #
+  #     - name: Install dependencies
+  #       run: pnpm install
+  #
+  #     - name: Create GitHub release
+  #       run: pnpm release --ci
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #
+  # run-migrations:
+  #   name: Run migrations
+  #   needs: [create-release]
+  #   runs-on: ubuntu-24.04
+  #   steps:
+  #     - name: Checkout monorepo
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0
+  #
+  #     - name: Install pnpm
+  #       uses: pnpm/action-setup@v4
+  #       with:
+  #         run_install: false
+  #
+  #     - name: Install Node.js 20
+  #       uses: actions/setup-node@v4
+  #       with:
+  #         node-version-file: "package.json"
+  #         architecture: "x64"
+  #         cache: "pnpm"
+  #
+  #     - name: Install dependencies
+  #       run: pnpm install
+  #
+  #     - name: Migrate database
+  #       env:
+  #         DATABASE_URL: ${{ secrets.DATABASE_URL }}
+  #         CI: true
+  #       run: |
+  #         echo "DATABASE_URL=$DATABASE_URL" >> packages/database/.env
+  #         echo "CI=$CI" >> packages/database/.env
+  #         pnpm run db:migrate
+  #         rm packages/database/.env
+  #
+  #     - name: Bump Zero schema version
+  #       env:
+  #         ZERO_UPSTREAM_DB: ${{ secrets.DATABASE_URL }}
+  #       run: |
+  #         echo "ZERO_UPSTREAM_DB=$ZERO_UPSTREAM_DB" >> packages/zero/.env
+  #         echo "CI=$CI" >> packages/zero/.env
+  #
+  #         pnpm run zero:migrate
+  #
+  #     - name: Deploy latest Zero permissions
+  #       env:
+  #         ZERO_UPSTREAM_DB: ${{ secrets.DATABASE_URL }}
+  #       run: |
+  #         # build database before deploying; otherwise drizzle schema won't load
+  #         turbo @avelin/database#build
+  #
+  #         pnpm run zero:deploy-permissions
+  #         rm packages/zero/.env
