ci/cd: deploy to production on every push (#148)
* Move IaC to separate repo

* Update release flow

Fix

Fix

Fixes

Fix

Fix

Fix

Add back image builds

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,6 +1,8 @@
 name: Release
 on:
-  workflow_dispatch:
+  push:
+    branches:
+      - main
 jobs:
   release:
     name: Release
@@ -12,8 +14,8 @@ jobs:
       id-token: write
 
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3
+      - name: Checkout monorepo
+        uses: actions/checkout@v4
         with:
           fetch-depth: 0
 
@@ -44,9 +46,6 @@ jobs:
           NEW_VERSION=$(pnpm release --ci --release-version | tail -n1)
 
           echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
-
-      # - name: Set up QEMU
-      #   uses: docker/setup-qemu-action@v3
 
       - name: Setup Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -111,17 +110,20 @@ jobs:
             ghcr.io/avelinapp/migrate:v${{ steps.next_version.outputs.new_version }}
           platforms: linux/amd64
 
-      - name: Bump version
-        run: |
-          pnpm release --ci
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Checkout IaC repo
+        uses: actions/checkout@v4
+        with:
+          repository: avelinapp/iac
+          token: ${{ secrets.GH_IAC_SECRET }}
+          fetch-depth: 0
+          path: iac
 
-      - name: Update K8s manifests for apps
+      - name: Update K8s manifests in IaC repo
+        working-directory: iac
         run: |
           VERSION=v${{ steps.next_version.outputs.new_version }}
           apps=("web" "api" "sync")
-          manifests_dir="deploy/k8s"
+          manifests_dir="k8s"
           for app in "${apps[@]}"; do
             manifest="$manifests_dir/${app}-deploy.yaml"
             if [ -f "$manifest" ]; then
@@ -133,22 +135,29 @@ jobs:
             fi
           done
 
-      - name: Update K8s manifests for db migration helper
-        run: |
-          VERSION=v${{ steps.next_version.outputs.new_version }}
           app="migrate"
-          manifests_dir="deploy/k8s"
           manifest="$manifests_dir/db-migration-job.yaml"
-            if [ -f "$manifest" ]; then
-              echo "Updating image tag in $manifest to $VERSION"
-              yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/$app:$VERSION\"" "$manifest"
-            else
-              echo "Manifest file $manifest not found!"
-              exit 1
-            fi
+          if [ -f "$manifest" ]; then
+            echo "Updating image tag in $manifest to $VERSION"
+            yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/$app:$VERSION\"" "$manifest"
+          else
+            echo "Manifest file $manifest not found!"
+            exit 1
+          fi
 
-      - name: Create release PR
-        uses: peter-evans/create-pull-request@v7
-        with:
-          title: 'v${{ steps.next_version.outputs.new_version }}'
-          assignees: 'bazzadev'
+      - name: Commit changes to IaC repo
+        working-directory: iac
+        run: |
+          git pull
+          git config user.name "${{ github.actor }}"
+          git config user.email "${{ github.actor }}@users.noreply.github.com"
+
+          git add .
+          git commit -m "chore: update manifests to v${{ steps.next_version.outputs.new_version }}"
+          git push
+
+      - name: Create GitHub release
+        run: |
+          pnpm release --ci
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
