feat: disable anonymous sessions (#253)
* progress

* Done

---------

Co-authored-by: Kian Bazza <kianbazza@Kians-MacBook-Pro.local>

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -76,8 +76,8 @@ jobs:
         include:
           - app: web
             dockerfile: ./apps/web/Dockerfile
-          - app: web-bun
-            dockerfile: ./apps/web/Dockerfile.bun
+          # - app: web-bun
+          #   dockerfile: ./apps/web/Dockerfile.bun
           - app: api
             dockerfile: ./apps/api/Dockerfile
           - app: sync
@@ -128,27 +128,27 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-      - name: Build and Push ${{ matrix.app }}
-        if: ${{ matrix.app == 'web-bun' }}
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: ${{ matrix.dockerfile }}
-          push: true
-          platforms: linux/amd64
-          tags: |
-            ghcr.io/avelinapp/web:latest-bun-amd64
-            ghcr.io/avelinapp/web:${{ github.sha }}-bun-amd64
-            ghcr.io/avelinapp/web:${{ needs.prepare.outputs.new_version }}-bun-amd64
-            ghcr.io/avelinapp/web:v${{ needs.prepare.outputs.new_version }}-bun-amd64
-          build-args: |
-            NEXT_PUBLIC_APP_URL=https://avelin.app
-            NEXT_PUBLIC_API_URL=https://api.avelin.app
-            NEXT_PUBLIC_SYNC_URL=wss://sync.avelin.app
-            NEXT_PUBLIC_ZERO_URL=https://zero.avelin.app
-            NEXT_PUBLIC_POSTHOG_KEY=phc_ClqyvBT8tnlp26PQhvbWZHuSMvrn6gq0CZEqfzwI3JC
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+      # - name: Build and Push ${{ matrix.app }}
+      #   if: ${{ matrix.app == 'web-bun' }}
+      #   uses: docker/build-push-action@v6
+      #   with:
+      #     context: .
+      #     file: ${{ matrix.dockerfile }}
+      #     push: true
+      #     platforms: linux/amd64
+      #     tags: |
+      #       ghcr.io/avelinapp/web:latest-bun-amd64
+      #       ghcr.io/avelinapp/web:${{ github.sha }}-bun-amd64
+      #       ghcr.io/avelinapp/web:${{ needs.prepare.outputs.new_version }}-bun-amd64
+      #       ghcr.io/avelinapp/web:v${{ needs.prepare.outputs.new_version }}-bun-amd64
+      #     build-args: |
+      #       NEXT_PUBLIC_APP_URL=https://avelin.app
+      #       NEXT_PUBLIC_API_URL=https://api.avelin.app
+      #       NEXT_PUBLIC_SYNC_URL=wss://sync.avelin.app
+      #       NEXT_PUBLIC_ZERO_URL=https://zero.avelin.app
+      #       NEXT_PUBLIC_POSTHOG_KEY=phc_ClqyvBT8tnlp26PQhvbWZHuSMvrn6gq0CZEqfzwI3JC
+      #     cache-from: type=gha
+      #     cache-to: type=gha,mode=max
 
   build-push-arm64:
     name: Build & push ${{ matrix.app }} - ARM64
@@ -163,8 +163,8 @@ jobs:
         include:
           - app: web
             dockerfile: ./apps/web/Dockerfile
-          - app: web-bun
-            dockerfile: ./apps/web/Dockerfile.bun
+          # - app: web-bun
+          #   dockerfile: ./apps/web/Dockerfile.bun
           - app: api
             dockerfile: ./apps/api/Dockerfile
           - app: sync
@@ -215,27 +215,27 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
 
-      - name: Build and Push ${{ matrix.app }}
-        if: ${{ matrix.app == 'web-bun' }}
-        uses: docker/build-push-action@v6
-        with:
-          context: .
-          file: ${{ matrix.dockerfile }}
-          push: true
-          platforms: linux/arm64
-          tags: |
-            ghcr.io/avelinapp/web:latest-bun-arm64
-            ghcr.io/avelinapp/web:${{ github.sha }}-bun-arm64
-            ghcr.io/avelinapp/web:${{ needs.prepare.outputs.new_version }}-bun-arm64
-            ghcr.io/avelinapp/web:v${{ needs.prepare.outputs.new_version }}-bun-arm64
-          build-args: |
-            NEXT_PUBLIC_APP_URL=https://avelin.app
-            NEXT_PUBLIC_API_URL=https://api.avelin.app
-            NEXT_PUBLIC_SYNC_URL=wss://sync.avelin.app
-            NEXT_PUBLIC_ZERO_URL=https://zero.avelin.app
-            NEXT_PUBLIC_POSTHOG_KEY=phc_ClqyvBT8tnlp26PQhvbWZHuSMvrn6gq0CZEqfzwI3JC
-          cache-from: type=gha
-          cache-to: type=gha,mode=max
+      # - name: Build and Push ${{ matrix.app }}
+      #   if: ${{ matrix.app == 'web-bun' }}
+      #   uses: docker/build-push-action@v6
+      #   with:
+      #     context: .
+      #     file: ${{ matrix.dockerfile }}
+      #     push: true
+      #     platforms: linux/arm64
+      #     tags: |
+      #       ghcr.io/avelinapp/web:latest-bun-arm64
+      #       ghcr.io/avelinapp/web:${{ github.sha }}-bun-arm64
+      #       ghcr.io/avelinapp/web:${{ needs.prepare.outputs.new_version }}-bun-arm64
+      #       ghcr.io/avelinapp/web:v${{ needs.prepare.outputs.new_version }}-bun-arm64
+      #     build-args: |
+      #       NEXT_PUBLIC_APP_URL=https://avelin.app
+      #       NEXT_PUBLIC_API_URL=https://api.avelin.app
+      #       NEXT_PUBLIC_SYNC_URL=wss://sync.avelin.app
+      #       NEXT_PUBLIC_ZERO_URL=https://zero.avelin.app
+      #       NEXT_PUBLIC_POSTHOG_KEY=phc_ClqyvBT8tnlp26PQhvbWZHuSMvrn6gq0CZEqfzwI3JC
+      #     cache-from: type=gha
+      #     cache-to: type=gha,mode=max
 
   create-manifests:
     name: Create image manifests
@@ -285,37 +285,37 @@ jobs:
             docker manifest push ghcr.io/avelinapp/$app:v$VERSION
           done
 
-      - name: Create and push final manifests (SHA, version)
-        run: |
-          VERSION=${{ needs.prepare.outputs.new_version }}
-
-          APPS=("web")
-
-          for app in "${APPS[@]}"; do
-            DIGEST_AMD64=$(docker manifest inspect ghcr.io/avelinapp/$app:${{ github.sha }}-bun-amd64 | jq -r '.manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest')
-            DIGEST_ARM64=$(docker manifest inspect ghcr.io/avelinapp/$app:${{ github.sha }}-bun-arm64 | jq -r '.manifests[] | select(.platform.architecture == "arm64" and .platform.os == "linux") | .digest')
-
-            docker manifest create \
-              ghcr.io/avelinapp/$app:${{ github.sha }}-bun \
-              --amend ghcr.io/avelinapp/$app@$DIGEST_AMD64 \
-              --amend ghcr.io/avelinapp/$app@$DIGEST_ARM64
-
-            docker manifest push ghcr.io/avelinapp/$app:${{ github.sha }}-bun
-
-            docker manifest create \
-              ghcr.io/avelinapp/$app:$VERSION-bun \
-              --amend ghcr.io/avelinapp/$app@$DIGEST_AMD64 \
-              --amend ghcr.io/avelinapp/$app@$DIGEST_ARM64
-
-            docker manifest push ghcr.io/avelinapp/$app:$VERSION-bun
-
-            docker manifest create \
-              ghcr.io/avelinapp/$app:v$VERSION-bun \
-              --amend ghcr.io/avelinapp/$app@$DIGEST_AMD64 \
-              --amend ghcr.io/avelinapp/$app@$DIGEST_ARM64
-
-            docker manifest push ghcr.io/avelinapp/$app:v$VERSION-bun
-          done
+      # - name: Create and push final manifests (SHA, version)
+      #   run: |
+      #     VERSION=${{ needs.prepare.outputs.new_version }}
+      #
+      #     APPS=("web")
+      #
+      #     for app in "${APPS[@]}"; do
+      #       DIGEST_AMD64=$(docker manifest inspect ghcr.io/avelinapp/$app:${{ github.sha }}-bun-amd64 | jq -r '.manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest')
+      #       DIGEST_ARM64=$(docker manifest inspect ghcr.io/avelinapp/$app:${{ github.sha }}-bun-arm64 | jq -r '.manifests[] | select(.platform.architecture == "arm64" and .platform.os == "linux") | .digest')
+      #
+      #       docker manifest create \
+      #         ghcr.io/avelinapp/$app:${{ github.sha }}-bun \
+      #         --amend ghcr.io/avelinapp/$app@$DIGEST_AMD64 \
+      #         --amend ghcr.io/avelinapp/$app@$DIGEST_ARM64
+      #
+      #       docker manifest push ghcr.io/avelinapp/$app:${{ github.sha }}-bun
+      #
+      #       docker manifest create \
+      #         ghcr.io/avelinapp/$app:$VERSION-bun \
+      #         --amend ghcr.io/avelinapp/$app@$DIGEST_AMD64 \
+      #         --amend ghcr.io/avelinapp/$app@$DIGEST_ARM64
+      #
+      #       docker manifest push ghcr.io/avelinapp/$app:$VERSION-bun
+      #
+      #       docker manifest create \
+      #         ghcr.io/avelinapp/$app:v$VERSION-bun \
+      #         --amend ghcr.io/avelinapp/$app@$DIGEST_AMD64 \
+      #         --amend ghcr.io/avelinapp/$app@$DIGEST_ARM64
+      #
+      #       docker manifest push ghcr.io/avelinapp/$app:v$VERSION-bun
+      #     done
 
   update-manifests:
     name: Update manifests in avelinapp/iac
@@ -350,19 +350,19 @@ jobs:
             fi
           done
 
-      - name: Update K8s manifests (web-bun)
-        working-directory: avelinapp-iac
-        run: |
-          VERSION=v${{ needs.prepare.outputs.new_version }}-bun
-          manifests_dir="gitops/cluster-apps/avelin"
-          manifest="$manifests_dir/web/web-bun-deploy.yaml"
-          if [ -f "$manifest" ]; then
-            echo "Updating image tag in $manifest to $VERSION"
-            yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/web:$VERSION\"" "$manifest"
-          else
-            echo "Manifest file $manifest not found!"
-            exit 1
-          fi
+      # - name: Update K8s manifests (web-bun)
+      #   working-directory: avelinapp-iac
+      #   run: |
+      #     VERSION=v${{ needs.prepare.outputs.new_version }}-bun
+      #     manifests_dir="gitops/cluster-apps/avelin"
+      #     manifest="$manifests_dir/web/web-bun-deploy.yaml"
+      #     if [ -f "$manifest" ]; then
+      #       echo "Updating image tag in $manifest to $VERSION"
+      #       yq e -i ".spec.template.spec.containers[].image = \"ghcr.io/avelinapp/web:$VERSION\"" "$manifest"
+      #     else
+      #       echo "Manifest file $manifest not found!"
+      #       exit 1
+      #     fi
 
       - name: Update Zero server manifest
         working-directory: avelinapp-iac
